export enum ErrorType {
    LOGGED_IN_ON_OTHER_DEVICE = "LOGGED_IN_ON_OTHER_DEVICE",
    INACTIVE_ACCOUNT = "INACTIVE_ACCOUNT",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    NO_REFRESHTOKEN_PRESENT = "NO_REFRESHTOKEN_PRESENT",
    REFRESHTOKEN_EXPIRED = "REFRESHTOKEN_EXPIRED",
    SOCKETIO_TOKEN_EXPIRED = "SOKCKETIO_TOKEN_EXPIRED",
    SOCKETIO_TOKEN_MISSING = "SOKCKETIO_TOKEN_MISSING",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    TOKEN_MISSING = "TOKEN_MISSING",
}
